//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinTracker {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FinTrackRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FinTrackRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FinTracker.FinTrackRes", typeof(FinTrackRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewer deleted successfully.
        /// </summary>
        internal static string REV_DELETE {
            get {
                return ResourceManager.GetString("REV_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while deleting the reviewer information.
        /// </summary>
        internal static string REV_DELETE_ERR {
            get {
                return ResourceManager.GetString("REV_DELETE_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while loading the reviewer information.
        /// </summary>
        internal static string REV_LOAD_ERR {
            get {
                return ResourceManager.GetString("REV_LOAD_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewer saved successfully.
        /// </summary>
        internal static string REV_SAVE {
            get {
                return ResourceManager.GetString("REV_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while saving the Reviewer details.
        /// </summary>
        internal static string REV_SAVE_ERR {
            get {
                return ResourceManager.GetString("REV_SAVE_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User deleted successfully.
        /// </summary>
        internal static string USER_DELETE {
            get {
                return ResourceManager.GetString("USER_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while deleting the user.
        /// </summary>
        internal static string USER_DELETE_ERR {
            get {
                return ResourceManager.GetString("USER_DELETE_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while getting the user information.
        /// </summary>
        internal static string USER_RETRIEVE_ERR {
            get {
                return ResourceManager.GetString("USER_RETRIEVE_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User saved successfully.
        /// </summary>
        internal static string USER_SAVE {
            get {
                return ResourceManager.GetString("USER_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while saving the user information.
        /// </summary>
        internal static string USER_SAVE_ERR {
            get {
                return ResourceManager.GetString("USER_SAVE_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User updated successfully.
        /// </summary>
        internal static string USER_UPDATE {
            get {
                return ResourceManager.GetString("USER_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while updating the user information.
        /// </summary>
        internal static string USER_UPDATE_ERR {
            get {
                return ResourceManager.GetString("USER_UPDATE_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading the dashboard charts.
        /// </summary>
        internal static string WM_CHART_ERR_MSG {
            get {
                return ResourceManager.GetString("WM_CHART_ERR_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not able to load the report.
        /// </summary>
        internal static string WM_REPORT_LOAD_ERR {
            get {
                return ResourceManager.GetString("WM_REPORT_LOAD_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while getting the work maintenance.
        /// </summary>
        internal static string WM_RETRIEVE_ERR {
            get {
                return ResourceManager.GetString("WM_RETRIEVE_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work item saved successfully.
        /// </summary>
        internal static string WM_SAVE {
            get {
                return ResourceManager.GetString("WM_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while saving the work item information.
        /// </summary>
        internal static string WM_SAVE_ERR {
            get {
                return ResourceManager.GetString("WM_SAVE_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work item submitted successfully.
        /// </summary>
        internal static string WM_UPDATE {
            get {
                return ResourceManager.GetString("WM_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work item updated and locked for editing.
        /// </summary>
        internal static string WM_UPDATE_APPR_ERR_FIND {
            get {
                return ResourceManager.GetString("WM_UPDATE_APPR_ERR_FIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while updating the work maintenance.
        /// </summary>
        internal static string WM_UPDATE_ERR {
            get {
                return ResourceManager.GetString("WM_UPDATE_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work item sent back to the processor for Rework.
        /// </summary>
        internal static string WM_UPDATE_REW {
            get {
                return ResourceManager.GetString("WM_UPDATE_REW", resourceCulture);
            }
        }
    }
}
